"""
=============================================================================
 github_commenter.py — GitHub PR Comment Publisher
=============================================================================
 Posts formatted review comments to GitHub PRs via the REST API.
=============================================================================
"""

import os
import requests
from typing import Dict, Any, List

SEVERITY_MARKER = {"Critical": "[!]", "High": "[!!]", "Medium": "[~]", "Low": "[-]"}
SEVERITY_LABEL = {"Critical": "CRITICAL", "High": "HIGH", "Medium": "MEDIUM", "Low": "LOW"}


def post_review_comment(repo, pr_number, github_token, review, head_sha):
    """Post the AI review as a PR comment and inline review comments."""
    summary = review.get("summary", {})
    issues = review.get("issues", [])
    body = _build_comment_body(summary, issues)
    _post_issue_comment(repo, pr_number, github_token, body)
    if issues:
        _post_inline_review(repo, pr_number, github_token, issues, head_sha)
    print(f"[OK] Review posted successfully to PR #{pr_number}")


def _build_comment_body(summary, issues):
    score = summary.get("score", 0)
    total = summary.get("total_issues", 0)
    files = summary.get("files_reviewed", 0)

    if score >= 90:
        score_color, score_label = "[PASS]", "Excellent"
    elif score >= 75:
        score_color, score_label = "[OK]", "Good"
    elif score >= 50:
        score_color, score_label = "[WARN]", "Needs Improvement"
    else:
        score_color, score_label = "[FAIL]", "Poor"

    lines = [
        "# AI Code Review Results\n", "---\n",
        "## Code Quality Score\n",
        f"### {score_color} **{score} / 100** -- _{score_label}_\n",
        "## Review Summary\n",
        "| Metric | Value |", "|--------|-------|",
        f"| Files Reviewed | **{files}** |",
        f"| Total Issues | **{total}** |",
        f"| Critical | **{summary.get('critical', 0)}** |",
        f"| High | **{summary.get('high', 0)}** |",
        f"| Medium | **{summary.get('medium', 0)}** |",
        f"| Low | **{summary.get('low', 0)}** |", "",
    ]

    if issues:
        lines.extend(["---\n", "## Detailed Findings\n"])
        for i, issue in enumerate(issues, 1):
            sev = issue.get("severity", "Medium")
            marker = SEVERITY_MARKER.get(sev, "[?]")
            label = SEVERITY_LABEL.get(sev, "INFO")
            lines.append(f"### {marker} Issue #{i} -- `{label}` | {issue.get('category', 'General')}\n")
            lines.append(f"**File:** `{issue.get('file', 'Unknown')}` | **Line:** `{issue.get('line', 0)}`\n")
            lines.append(f"**Problem:**\n> {issue.get('issue', '')}\n")
            lines.append(f"**Suggested Fix:**\n> {issue.get('fix', '')}\n")
            cb = issue.get("code_before", "")
            ca = issue.get("code_after", "")
            if cb and ca:
                lines.append("<details><summary>Code Suggestion</summary>\n")
                lines.append(f"**Before:**\n```csharp\n{cb}\n```\n")
                lines.append(f"**After:**\n```csharp\n{ca}\n```\n</details>\n")
    else:
        lines.extend(["---\n", "## No Issues Found\n", "Great job! The code looks clean.\n"])

    lines.extend(["---\n", "_Generated by **AI Code Reviewer** powered by Groq._"])
    return "\n".join(lines)


def _post_issue_comment(repo, pr_number, token, body):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json"}
    resp = requests.post(url, headers=headers, json={"body": body})
    if resp.status_code not in (200, 201):
        print(f"[WARN] Failed to post comment: {resp.status_code}\n{resp.text}")
    else:
        print("[OK] Summary comment posted.")


def _post_inline_review(repo, pr_number, token, issues, head_sha):
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/reviews"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json"}
    comments = []
    for issue in issues:
        line = issue.get("line", 0)
        if line <= 0:
            continue
        sev = issue.get("severity", "Medium")
        marker = SEVERITY_MARKER.get(sev, "[?]")
        body = (f"{marker} **{sev}** -- {issue.get('category', 'General')}\n\n"
                f"**Issue:** {issue.get('issue', '')}\n\n"
                f"**Fix:** {issue.get('fix', '')}")
        ca = issue.get("code_after", "")
        if ca:
            body += f"\n\n```suggestion\n{ca}\n```"
        comments.append({"path": issue.get("file", ""), "line": line, "body": body})

    if not comments:
        return
    payload = {"commit_id": head_sha, "body": "AI Code Review -- see inline comments.", "event": "COMMENT", "comments": comments}
    resp = requests.post(url, headers=headers, json=payload)
    if resp.status_code not in (200, 201):
        print(f"[WARN] Inline review returned {resp.status_code}\n{resp.text}")
    else:
        print(f"[OK] {len(comments)} inline comment(s) posted.")
