"""
=============================================================================
 review.py — Main Orchestrator
=============================================================================
 Entry point for the AI Code Review GitHub Action.
 
 Flow:
   1. Read environment variables (PR number, repo, tokens)
   2. Fetch changed C# files from the PR diff
    3. Send the diff to Groq for review
   4. Post the structured review back to the PR as comments
=============================================================================
"""

import os
import sys
import json
from datetime import datetime, timezone

# Ensure repository root is importable when running `python scripts/review.py`.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    """Run the end-to-end AI code review pipeline."""
    print("=" * 60)
    print("AI Code Review for C# -- Starting...")
    print(f"Time: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Read environment variables
    # ------------------------------------------------------------------
    github_token = os.environ.get("GITHUB_TOKEN")
    groq_key = os.environ.get("GROQ_API_KEY")
    pr_number = os.environ.get("PR_NUMBER")
    repo = os.environ.get("REPO_FULL_NAME")
    head_sha = os.environ.get("PR_HEAD_SHA", "")

    if not all([github_token, groq_key, pr_number, repo]):
        print("[ERROR] Missing required environment variables.")
        print("   Required: GITHUB_TOKEN, GROQ_API_KEY, PR_NUMBER, REPO_FULL_NAME")
        sys.exit(1)

    pr_number = int(pr_number)
    print(f"Repository : {repo}")
    print(f"PR Number  : #{pr_number}")
    print(f"Head SHA   : {head_sha[:8]}...")

    # ------------------------------------------------------------------
    # 2. Fetch and parse the PR diff (only C# files)
    # ------------------------------------------------------------------
    from scripts.diff_parser import get_pr_changed_files, format_diff_for_prompt

    print("\nFetching changed C# files...")
    changed_files = get_pr_changed_files(repo, pr_number, github_token)

    if not changed_files:
        print("[INFO] No C# files changed in this PR. Skipping review.")
        _post_no_cs_comment(repo, pr_number, github_token)
        return

    print(f"   Found {len(changed_files)} C# file(s):")
    for f in changed_files:
        print(f"   • {f.filename} (+{f.additions}/-{f.deletions})")

    diff_text = format_diff_for_prompt(changed_files)
    print(f"   Total diff size: {len(diff_text)} characters")

    # ------------------------------------------------------------------
    # 3. Send to AI for review
    # ------------------------------------------------------------------
    from scripts.ai_reviewer import review_code

    print("\nSending code to AI reviewer (Groq)...")
    review = review_code(diff_text, len(changed_files))

    summary = review.get("summary", {})
    issues = review.get("issues", [])
    print(f"\nReview Complete:")
    print(f"   Score    : {summary.get('score', 'N/A')} / 100")
    print(f"   Issues   : {summary.get('total_issues', 0)}")
    print(f"   Critical : {summary.get('critical', 0)}")
    print(f"   High     : {summary.get('high', 0)}")
    print(f"   Medium   : {summary.get('medium', 0)}")
    print(f"   Low      : {summary.get('low', 0)}")

    # ------------------------------------------------------------------
    # 4. Post review comments to the PR
    # ------------------------------------------------------------------
    from scripts.github_commenter import post_review_comment

    print("\nPosting review to PR...")
    post_review_comment(repo, pr_number, github_token, review, head_sha)

    print("\n" + "=" * 60)
    print("[OK] AI Code Review completed successfully!")
    print("=" * 60)


def _post_no_cs_comment(repo, pr_number, token):
    """Post a comment when no C# files are found."""
    import requests
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    body = (
        "# AI Code Review Results\n\n"
        "**No C# files were changed in this PR.**\n\n"
        "The AI reviewer only analyzes `.cs` files. "
        "No review is needed for this PR.\n\n"
        "---\n"
        "_Generated by **AI Code Reviewer** powered by Groq._"
    )
    requests.post(url, headers=headers, json={"body": body})
    print("[INFO] Posted 'no C# files' comment.")


if __name__ == "__main__":
    main()
